### ISSUE TITLE
Creating network from paths overrides the directionality.

### ISSUE THREAD

**Issue by user1246638** [uzhdag/pathpy#37] opened 2018-11-13 09:46 UTC
```
p = pp.Paths()
for i in [(0,1),(1,2),(2,0),(1,3),(3,4),(5,4),(5,3),(5,6),(6,3)]:
    p.add_path(i)
g_u = pp.Network(directed = False)
g_u.from_paths(p)
```
gives a directed network when plotted.

**Comment by verginer** [comment] 2018-11-14 11:20
hi @user1246638, `Network.from_paths()` is a class method (indicated by the `cls` in the signature) which will not alter the existing network but create a new one. In other words the fact that you declare `Network(directed = False)` is only applicable to `g_u` and has no effect on any other object.

In fact the function `from_paths` should never be called from an instantiated object such as `g_u`, maybe we need a warning in the documentation saying as much.

With regard to a network created from a `Paths` object, do you have a specific application in mind where it should be undirected? Since the paths analogy implies a directionality which should be preserved I would not offer the ability to create undirected networks from paths directly.
What could be more useful also for the future is to create a `Network.to_undirected()` function also found in networkx.

**Comment by IngoScholtes** [comment] 2019-02-14 22:19
Closing this, as this is expected behavior.

**Closed by IngoScholtes** 2019-02-14 22:19 UTC
Labels: documentation, enhancement, wontfix
